### ISSUE TITLE
Comprehensive Testing

### ISSUE THREAD

**Issue by kenkirkley** [Aggie-Web-Developers/awd-project-sama#51]
Assignees to this issue will test all of the pages of the website, searching for bugs in functionality, format, and responsiveness.

The testing criteria is as follows:

1. Test the functionality. Do all of the actions on the page (links, buttons, inputs) work as intended in normal cases? Additionally, do these actions work when given edge case parameters, such as script injections, foreign characters, and empty inputs?
2. Review the layout and scripts/console. Are there any unexpected CSS interactions? Does the layout match the design mockup? Are there any console.log statements still present? Are there JS errors in the console?
3. Review the responsiveness. Open the Dev Tools in google chrome, and activate the responsive view (top left of the dev tools interface). Adjust the width by sliding the left and right borders. Are there any strange CSS behaviors at certain widths? In addition, you can choose sample devices at the top of the responsive view. Test the pages on these devices as well. The minimum width we will be accommodating is 320px.

If you come across anything that does not meet the criteria, make note of them so that we can go back and fix these issues.

**Comment by tonyy007** [comment]
The newsletter tab isn't working.

**Comment by kryuki** [comment]
Add another panel to access portal/newsletter.

**Comment by kryuki** [comment]
One can enter the portal page just by typing /portal in the route?

https://user-images.githubusercontent.com/36336987/131233870-c2f14c31-3dbf-456a-af45-87eb7430c6fa.mp4

**Comment by kryuki** [comment]
What does this "Read now" button on the newsletter page do?

![readnow](https://user-images.githubusercontent.com/36336987/131233913-f6159814-a51c-4b39-a511-ca429c1390f7.PNG)

**Comment by kenkirkley** [comment]
Join discord buttons and Read more newsletter buttons need links

**Comment by kenkirkley** [comment]
contact us thank you page

**Comment by kryuki** [comment]
If the title of the newsletter is more than 75 characters, it freezes when uploading it.

**Comment by kenkirkley** [comment]
> I think clicking on the Aggie-SAMA logo on this page should bring the user to the home page.
> 
>  Record_2021_08_26_13_53_21_749.mp4

This behavior emerges because the href of the <a> that the logo resides in is "/". When you are on the portal page, that takes you to /portal.

**Comment by kenkirkley** [comment]
Add most link to most recent newsletter to read more button on newsletter page

**Comment by kenkirkley** [comment]
> If the title of the newsletter is more than 75 characters, it freezes when uploading it.

Newsletter title max length changed to 200

**Comment by kenkirkley** [comment]
Newsletter table styling becomes unwieldy when the title of the newsletter is long. Some styling has been corrected with a fixed table layout.

**Comment by kenkirkley** [comment]
Instagram and facebook links in the header need to be set to SAMA's facebook and instagram
